# Generated by Django 3.1.2 on 2020-12-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockmktnews2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=1000, null=True)),
                ('Title', models.TextField(null=True)),
                ('Contents_summary', models.TextField(null=True)),
                ('Category', models.CharField(max_length=1000, null=True)),
                ('Publisher', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=4000, null=True)),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='WordCloud',
        ),
    ]
