# Generated by Django 3.1.2 on 2020-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201206_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMktNews',
            fields=[
                ('pk_url', models.CharField(db_column='Pk_url', max_length=250, primary_key=True, serialize=False)),
                ('section', models.CharField(db_column='Section', max_length=30)),
                ('title', models.CharField(db_column='Title', max_length=999)),
                ('contents_summary', models.TextField(db_column='Contents_summary')),
                ('category', models.CharField(db_column='Category', max_length=20)),
                ('publisher', models.CharField(db_column='Publisher', max_length=300)),
                ('url', models.TextField(db_column='Url')),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
            ],
            options={
                'db_table': 'StockMktNews',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='stockmktnews2',
        ),
    ]
